version: "3.4"

services:
  traefik:
    build:
      context: ./Traefik
    command: "traefik -c /etc/traefik/config/config.toml"
    healthcheck:
      interval: 5s
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.port=8080
      - traefik.enable=true
      - traefik.docker.network=infrastructure_default
      - traefik.frontend.rule=Host:traefik.localhost

  postgres:
    image: postgres
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Password1234
    networks:
      default:
        aliases:
          - postgres

  rabbitmq:
    build: ./RabbitMq
    ports:
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
    healthcheck:
      test: rabbitmq-diagnostics -q alarms || exit 1
      interval: 30s
      start_period: 1m
    networks:
      default:
        aliases:
          - rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq

networks:
  default:
    driver: bridge

volumes:
  postgres:
    driver: local
  rabbitmq:
    driver: local