
# Enable debug logging
logLevel = "DEBUG"

# Enable admin interface
[api]
  dashboard = true
  [api.statistics]
    recentErrors = 100

# Allow metrics to be exposed on dashboard
[metrics]

# Allow Docker healthcheck to ping
[ping]

# Enable Docker Swarm mode
[docker]
  swarmmode = false
  watch = true
  exposedbydefault = false
  endpoint = "unix:///var/run/docker.sock"
  network = "infrastructure"

